services:
  labelstudio:
    image: heartexlabs/label-studio:1.23.0
    container_name: labelstudio
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD}

      - DATA_UPLOAD_MAX_NUMBER_FILES=10000
      - DATA_UPLOAD_MAX_MEMORY_SIZE=10737418240

      - LABEL_STUDIO_HOST=https://${LABEL_STUDIO_DOMAIN}
      - LABEL_STUDIO_PORT=8080

      - DJANGO_ALLOWED_HOSTS=${LABEL_STUDIO_DOMAIN},localhost,127.0.0.1
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://${LABEL_STUDIO_DOMAIN}
      - CSRF_TRUSTED_ORIGINS=https://${LABEL_STUDIO_DOMAIN}

      - USE_X_FORWARDED_HOST=1
      - USE_X_FORWARDED_PORT=1
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https

      - CSRF_COOKIE_SECURE=1
      - SESSION_COOKIE_SECURE=1
      - SESSION_COOKIE_SAMESITE=Lax

    volumes:
      - ${LABELSTUDIO_DATA_PATH:-./data/labelstudio}:/label-studio/data